AWSTemplateFormatVersion: "2010-09-09"
Description: "'Evendale Storage Gateway CFT V1.1'"
Parameters:
  createdBy:
    Default: "503342590"
    Description: 'Who to email when something goes wrong. This is where your SSO goes'
    Type: String
  uai:
    Default: "1100759079"
    Description: "The UAI used to track billing and costs"
    Type: String
  env:
    Default: "prod"
    Description: 'Environment Label. Must be on of these prod, qa, dev, build, nonprod. Everything also need to be lowercase.'
    Type: String
  stackName:
    Default: "cf-av-sgw-evendale-gwy02-atd-dfars"
    Description: 'Must be the name of the stack that this cft is going to apart of. Must be between 1 and 255 characters and cannot start with a number'
    Type: String
  siteName:
    Default: "evendale"
    Type: String
  fileShareName:
    Default: "atd-dfars"
    Type: String
  loggingBucketName:
    Default: "av-goveast-658233819642-s3-logs"
    Type: String
    Description: "Name of the logging bucket for the S3 Access Logs"
  noncurrentDays:   
    Default: 5
    Type: Number
    Description: "Number of days to retain a noncurrent version of a file"
  noncurrentGlacierDays:
    Default: 90
    Type: Number
    Description: "Number of days to retain a noncurrent version of a file in Gliacier backup directory"
Resources:
  KMSKEY:
    Type: AWS::KMS::Key
    Properties:
      Description: "Evendale Storage Gateway KMS key"
      EnableKeyRotation: True
      KeyPolicy:
        Id: key-default-1
        Version: '2012-10-17'
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Principal:
            AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
          Action: kms:*
          Resource: "*"
        - Sid: Allow access for Key Administrators
          Effect: Allow
          Principal:
            AWS:
            - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/av-bu-poweruser
            - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/av-cbts-storage-gateway
          Action:
          - kms:Create*
          - kms:Describe*
          - kms:Enable*
          - kms:List*
          - kms:Put*
          - kms:Update*
          - kms:Revoke*
          - kms:Disable*
          - kms:Get*
          - kms:Delete*
          - kms:TagResource
          - kms:UntagResource
          - kms:ScheduleKeyDeletion
          - kms:CancelKeyDeletion
          Resource: "*"
        - Sid: Allow use of the key
          Effect: Allow
          Principal:
            AWS: !GetAtt ReplicationRole.Arn
          Action:
          - kms:Encrypt
          - kms:Decrypt
          - kms:ReEncrypt*
          - kms:GenerateDataKey*
          - kms:DescribeKey
          Resource: "*"
        - Sid: Allow attachment of persistent resources
          Effect: Allow
          Principal:
            AWS: !GetAtt ReplicationRole.Arn
          Action:
          - kms:CreateGrant
          - kms:ListGrants
          - kms:RevokeGrant
          Resource: "*"
          Condition:
            Bool:
              kms:GrantIsForAWSResource: 'true'
      KeyUsage: ENCRYPT_DECRYPT
      Tags:
      - Key: uai
        Value: !Ref uai
      - Key: created_by
        Value: !Ref createdBy
      - Key: env
        Value: !Ref env
  KMSALIAS:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: 'alias/av-useast1-storage-gateway-evendale-gwy02-atd-dfars'
      #        - 'alias/av-usgoveast1-storage-gateway-{siteName}'
      #        - {siteName: !Ref siteName}
      TargetKeyId: !Ref KMSKEY
  S3Primary:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: "Private"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            KMSMasterKeyID: !Ref KMSKEY
            SSEAlgorithm: aws:kms
      BucketName: !Sub
      - 'av-sgw-${siteName}-${fileShareName}'
      - {siteName: !Ref siteName}
      LoggingConfiguration:
        DestinationBucketName: !Ref loggingBucketName
        LogFilePrefix: !Sub
        - 'av-sgw-${siteName}-${fileShareName}'
        - {siteName: !Ref siteName}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      ReplicationConfiguration:
        Role: !GetAtt ReplicationRole.Arn
        Rules:
        - Destination:
            Bucket: !GetAtt S3Secondary.Arn
            EncryptionConfiguration:
              ReplicaKmsKeyID: !GetAtt KMSKEY.Arn
            StorageClass: GLACIER
          Id: "Rule1"
          Priority: 1
          Filter:
            Prefix: ""
          DeleteMarkerReplication:
            Status: Enabled
          SourceSelectionCriteria:
            SseKmsEncryptedObjects:
              Status: Enabled
          Status: Enabled
      LifecycleConfiguration:
        Rules:
            - Id: av-version-retention-policy
              NoncurrentVersionExpiration:
                NoncurrentDays: !Ref noncurrentDays
              ExpiredObjectDeleteMarker: true
              Status: Enabled
      Tags:
      - Key: uai
        Value: !Ref uai
      - Key: created_by
        Value: !Ref createdBy
      - Key: env
        Value: !Ref env
      VersioningConfiguration:
        Status: Enabled
  S3Secondary:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: "Private"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            KMSMasterKeyID: !Ref KMSKEY
            SSEAlgorithm: aws:kms
      BucketName: !Sub
      - 'av-sgw-${siteName}-${fileShareName}-backup'
      - {siteName: !Ref siteName}
      LoggingConfiguration:
        DestinationBucketName: !Ref loggingBucketName
        LogFilePrefix: !Sub
        - 'av-sgw-${siteName}-${fileShareName}-backup'
        - {siteName: !Ref siteName}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      LifecycleConfiguration:
        Rules:
            - Id: av-version-retention-policy-glacier
              NoncurrentVersionExpiration:
                NoncurrentDays: !Ref noncurrentGlacierDays
              ExpiredObjectDeleteMarker: true
              Status: Enabled
      Tags:
      - Key: uai
        Value: !Ref uai
      - Key: created_by
        Value: !Ref createdBy
      - Key: env
        Value: !Ref env
      VersioningConfiguration:
        Status: Enabled
  ReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
      - 'av-sgw-${siteName}-${fileShareName}-bucket-backup-role'
      - {siteName: !Ref siteName}
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [s3.amazonaws.com]
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [storagegateway.amazonaws.com]
  BucketBackupPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - s3:ListBucket
          - s3:GetObjectVersion
          - s3:GetAccelerateConfiguration
          - s3:GetReplicationConfiguration
          - s3:GetObjectVersionForReplication
          - s3:GetObjectVersionAcl
          - s3:GetObjectVersionTagging
          - s3:GetObjectRetention
          - s3:GetObjectLegalHold
          - s3:ReplicateObject
          - s3:ReplicateDelete
          - s3:ReplicateTags
          - s3:ListBucket
          - s3:ListBucketMultipartUploads
          - s3:ListBucketVersions
          - s3:ListMultipartUploadParts
          - s3:GetBucketLocation
          - s3:GetBucketLocation
          - s3:GetBucketLogging
          - s3:GetBucketNotification
          - s3:GetBucketObjectLockConfiguration
          - s3:GetBucketPolicy
          - s3:GetBucketTagging
          - s3:GetBucketVersioning
          - s3:GetEncryptionConfiguration
          - s3:GetIntelligentTieringConfiguration
          - s3:GetInventoryConfiguration
          - s3:GetLifecycleConfiguration
          - s3:GetMetricsConfiguration
          - s3:GetObject
          - s3:GetObjectAcl
          - s3:GetObjectLegalHold
          - s3:GetObjectRetention
          - s3:GetBucketPolicyStatus
          - s3:GetObjectTagging
          - s3:GetObjectTorrent
          - s3:GetObjectVersionAcl
          - s3:GetObjectVersionForReplcation
          - s3:GetObjectVersionTagging
          - s3:GetObjectVersionTorrent
          - s3:GetReplicationConfiguration
          - s3:DeleteObjectTagging
          - s3:DeleteObjectVersionTagging
          - s3:PutBucketTagging
          - s3:PutObjectAcl
          - s3:PutObjectVersionTagging
          - s3:ReplicateTags
          - s3:AbortMultipartUpload
          - s3:DeleteObject
          - s3:DeleteObjectVersion
          - s3:PutAccelerateConfiguration
          - s3:PutBucketNotification
          - s3:PutBucketObjectLockConfiguration
          - s3:PutBucketOwnershipControls
          - s3:PutBucketVersioning
          - s3:PutEncryptionConfiguration
          - s3:PutIntelligentTieringConfiguration
          - s3:PutInventoryConfiguration
          - s3:PutLifecycleConfiguration
          - s3:PutMetricsConfiguration
          - s3:PutObject
          - s3:PutObjectAcl
          - s3:PutObjectLegalHold
          - s3:PutReplicationConfiguration
          - s3:ReplicateDelete
          - s3:ReplicateObject
          - s3:RestoreObject
          Effect: Allow
          Resource:
          - !Join ['', ['arn:aws-us-gov:s3:::', !Ref 'S3Primary']]
          - !Join ['', ['arn:aws-us-gov:s3:::', !Ref 'S3Primary','/*']]
        - Action:
          - s3:ReplicateObject
          - s3:ReplicateDelete
          - s3:ReplicateTags
          - s3:GetObjectVersionTagging
          Effect: Allow
          Condition:
            StringLikeIfExists:
              s3:x-amz-server-side-encryption:
              - aws:kms
              - AES256
              s3:x-amz-server-side-encryption-aws-kms-key-id:
              - !GetAtt KMSKEY.Arn
          Resource: !Join ['', ['arn:aws-us-gov:s3:::', !Ref 'S3Secondary', '/*']]
        - Action:
          - kms:Decrypt
          - kms:GenerateDataKey
          Effect: Allow
          Condition:
            StringLike:
              kms:ViaService: s3.us-gov-east-1.amazonaws.com
              kms:EncryptionContext:aws:s3:arn:
              - !Join ['', ['arn:aws-us-gov:s3:::', !Ref 'S3Primary']]
          Resource:
          - !GetAtt KMSKEY.Arn
        - Action:
          - kms:Encrypt
          Effect: Allow
          Condition:
            StringLike:
              kms:ViaService: s3.us-gov-east-1.amazonaws.com
              kms:EncryptionContext:aws:s3:arn:
              - !Join ['', ['arn:aws-us-gov:s3:::', !Ref 'S3Secondary']]
          Resource:
          - !GetAtt KMSKEY.Arn
      PolicyName: !Sub
      - 'av-sgw-${siteName}-${fileShareName}-bucket-backup-policy'
      - {siteName: !Ref siteName}
      Roles:
      - !Ref ReplicationRole
