- name: saml.yml
  url: https://fssfed.ge.com/fss
  username: "503416539"
  provider: Ping
  mfa: None
  mfa_device: ""
  mfa_prompt: false
  skip_verify: false
  timeout: 10
  aws_urn: urn:amazon:webservices:mfa
  aws_session_duration: 3600
  aws_profile: saml
  role_arn: ""
  region: ""
  http_attempts_count: ""
  http_retry_delay: ""
- name: saml
  url: https://fssfed.ge.com/fss
  username: "503416539"
  provider: Ping
  mfa: None
  mfa_device: ""
  mfa_prompt: false
  skip_verify: false
  timeout: 10
  aws_urn: urn:amazon:webservices:mfa
  aws_session_duration: 3600
  aws_profile: saml
  role_arn: ""
  region: ""
  http_attempts_count: ""
  http_retry_delay: ""
